[package]
name = "atree"
version = "0.4.3"
authors = ["Mac Lee <macthecadillac@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
